version:
os: linux
dist: bionic
virt: lxd
language: ruby
services:
  - docker
env:
  - COMPOSE_FILE=./docker-compose.yml

before_install:
  - docker-compose build --pull
  - docker-compose up -d

before_script:
  - docker-compose exec -T web RACK_ENV=test bundle exec rake db:create
script:
  - docker-compose exec -T web RACK_ENV=test bundle exec rake db:migrate
  - docker-compose exec -T web bundle exec rake rubocop
  - docker-compose exec -T bundle exec rake
after_script:
  # Cleanup docker-compose stuff.
  - docker-compose down --remove-orphans --rmi all