version: ~> 1.0
os: linux
dist: bionic
virt: lxd
language: ruby
rvm:
  - 2.4.1
services:
  - docker
env:
  - COMPOSE_FILE=./docker-compose.yml

install:
  - docker-compose build --pull

before_script:
  - docker-compose up -d
  - docker-compose exec -T web RACK_ENV=test bundle exec rake db:create
script:
  - docker-compose exec -T web RACK_ENV=test bundle exec rake db:migrate
  - docker-compose exec -T web bundle exec rake rubocop
  - docker-compose exec -T bundle exec rake
after_script:
  # Cleanup docker-compose stuff.
  - docker-compose down --remove-orphans --rmi all